apiVersion: v2
publisher: GlobalMaksimum
name: jupyterc
version: 0.14
type: Che Editor
displayName: Jupyter Custom Notebook
title: Jupyter Custom Notebook as Editor for Eclipse Che
description: Jupyter Custom Notebook as Editor for Eclipse Che
icon: https://jupyter.org/assets/main-logo.svg
category: Editor
repository: https://github.com/GlobalMaksimum/gbm-jupyter-docker-stack
firstPublicationDate: "2020-08-14"
spec:
  endpoints:
   -  name: "jupyterc"
      public: true
      targetPort: 8888
      attributes:
        protocol: http
        type: ide
        secure: true
        cookiesAuthEnabled: true
        discoverable: false
   -  name: "webviews"
      public: true
      targetPort: 8888
      attributes:
        protocol: http
        type: webview
        secure: true
        cookiesAuthEnabled: true
        discoverable: false
        unique: true
  containers:
    - name: jupyter-notebook
      image: "registry.192.168.39.247.nip.io/gbm/gbmjc:0.23"
      env:
        - name: JUPYTER_NOTEBOOK_DIR
          value: /projects
        - name: JUPYTER_GATEWAY_URL
          value: http://127.0.0.1:8887
        - name: JUPYTER_GATEWAY_HTTP_USER
          value: guest
        - name: JUPYTER_GATEWAY_HTTP_PWD
          value: guest-password
        - name: JUPYTER_GATEWAY_VALIDATE_CERT
          value: "false"
        - name: LOG_LEVEL
          value: DEBUG
      mountSources: true
      ports:
        - exposedPort: 8888
      memoryLimit: "512M"
