apiVersion: v2
publisher: ws-skeleton
name: jupyterc
version: 0.1
type: Che Editor
displayName: Jupyter Custom Notebook
title: Jupyter Custom Notebook as Editor for Eclipse Che
description: Jupyter Custom Notebook as Editor for Eclipse Che
icon: https://jupyter.org/assets/main-logo.svg
category: Editor
repository: https://github.com/ws-skeleton/che-editor-jupyter/
firstPublicationDate: "2020-08-14"
spec:
  endpoints:
   -  name: "jupyterc"
      public: true
      targetPort: 8888
      attributes:
        protocol: http
        type: ide
  containers:
   - name: jupyter-notebook
     image: "registry.192.168.39.191.nip.io/gbm/gbmjc:0.1"
     env:
         - name: JUPYTER_NOTEBOOK_DIR
           value: /projects
     mountSources: true
     ports:
         - exposedPort: 8888
     memoryLimit: "512M"